#!/bin/bash
set -e
set -o pipefail
if [ $# == 1 ]; then
  d="$1"
else
  mkdir -p res/server
  cd res/server
  rm -rf empty
  ls > a.txt
  md5sum * > b.txt
  md5sum * > c.txt
  mkdir empty
  cd ../../
  d="res/server"
fi
npm run build
node remote-sync.js server 8100 "$d" 2>server.error.log | tee server.out.log
